### ISSUE TITLE
Unable to import Yolov4

### ISSUE THREAD

**Issue by mon28** [Tushar-ml/DarkNeuron#6]
**Below error gets thrown when trying to import Yolov4 for Object Detection**
```
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from DarkNeurons import YOLOv4
  File "/data/mtare/darknet-py/venv/lib/python3.6/site-packages/DarkNeurons/__init__.py", line 2, in <module>
    from .YoloV4 import YOLOv4
  File "/data/mtare/darknet-py/venv/lib/python3.6/site-packages/DarkNeurons/YoloV4.py", line 12, in <module>
    from .realtime_detect import Real_Time_Tracking
  File "/data/mtare/darknet-py/venv/lib/python3.6/site-packages/DarkNeurons/realtime_detect.py", line 6, in <module>
    import pyautogui
  File "/data/mtare/darknet-py/venv/lib/python3.6/site-packages/pyautogui/__init__.py", line 241, in <module>
    import mouseinfo
  File "/data/mtare/darknet-py/venv/lib/python3.6/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/data/mtare/darknet-py/venv/lib64/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'
```

**To Reproduce**
1. In project directory in a file say train.py, import Yolov4 (from DarkNeurons import YOLOv4)
2. Run the above file with python 3.6 and all dependencies installed

**Expected behavior**
Expecting a successful import

**Desktop (please complete the following information):**
 - OS: Centos 7 (Linux)

**Additional context**
Output of pip freeze:
```
absl-py==0.9.0
astunparse==1.6.3
cachetools==4.1.0
certifi==2020.4.5.2
chardet==3.0.4
cycler==0.10.0
DarkNeurons==1.3.4
gast==0.3.3
google-auth==1.17.2
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.29.0
h5py==2.10.0
idna==2.9
importlib-metadata==1.6.1
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
Markdown==3.2.2
matplotlib==3.2.1
MouseInfo==0.1.3
numpy==1.18.5
oauthlib==3.1.0
opencv-python==4.2.0.34
opt-einsum==3.2.1
pandas==1.0.4
Pillow==7.1.2
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAutoGUI==0.9.50
PyGetWindow==0.0.8
PyMsgBox==1.0.8
pyparsing==2.4.7
pyperclip==1.8.0
PyRect==0.1.4
PyScreeze==0.1.26
python-dateutil==2.8.1
python3-xlib==0.15
PyTweening==1.0.3
pytz==2020.1
PyYAML==5.3.1
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.6
scipy==1.4.1
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.6.0.post3
tensorflow==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
urllib3==1.25.9
Werkzeug==1.0.1
wget==3.2
wrapt==1.12.1
zipp==3.1.0
```

**Comment by Tushar-ml** [comment]
This error comes when you try to open on kernels on cloud-like Kaggle, GCP in the further release this function will be improved.
This error comes due to the presence of PyAutoGUI Library in the module which are not supported on cloud kernels.

Thank you for having Patience

**Comment by Tushar-ml** [comment]
Are you satisfied with the Answer
Please comment yes or No

**Comment by mon28** [comment]
> This error comes when you try to open on kernels on cloud-like Kaggle, GCP in the further release this function will be improved.
> This error comes due to the presence of PyAutoGUI Library in the module which are not supported on cloud kernels.
> 
> Thank you for having Patience

How to resolve this? I am running it on a remote centos machine.

**Comment by Tushar-ml** [comment]
I m releasing a new Package version in just 30 mins. I will notify soon

**Comment by Tushar-ml** [comment]
New Release has been released 
pip install DarkNeurons==1.3.5

Now it is supportive on Remote servers

**Comment by mon28** [comment]
Thanks :)

**Comment by Tushar-ml** [comment]
I have released a new version for Files browsing flexibility. Read Readme.md file for detail.
Hope u like it
And share with the maximum audience.
-DarkNeurons
